version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/echamber/
permissions:
  - object: /var/www/echamber/
    owner: ec2-user
    group: www
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

