from repositories import BaseRepo
from models import PurchaseSingleOrder
from schemas import PurchaseSingleOrderIn, PurchaseSingleOrderUpdate

purchase_single_order_repo =BaseRepo[PurchaseSingleOrder, PurchaseSingleOrderIn, PurchaseSingleOrderUpdate](PurchaseSingleOrder)