"""medicine order form added

Revision ID: 06e0eb2e4d40
Revises: f837e6fef6fe
Create Date: 2022-06-13 11:45:06.083887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e0eb2e4d40'
down_revision = 'f837e6fef6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_orders', sa.Column('form', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_orders', 'form')
    # ### end Alembic commands ###
