"""medicine order remove for float

Revision ID: 08bc362a6c4e
Revises: 06e0eb2e4d40
Create Date: 2022-06-16 10:12:43.030468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08bc362a6c4e'
down_revision = '06e0eb2e4d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('service_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('generic', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('strength', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pharmaceuticals', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price_tp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price_mrp', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_discount_percent', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('form', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
