"""service order equal bug fix

Revision ID: 0a57af80a868
Revises: 3fd2bdec02f9
Create Date: 2022-06-11 17:56:19.714044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a57af80a868'
down_revision = '3fd2bdec02f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('service_name', sa.String(length=100), nullable=False))
    op.add_column('service_orders', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.add_column('service_orders', sa.Column('order_placement', sa.DateTime(), nullable=True))
    op.add_column('service_orders', sa.Column('order_completion', sa.DateTime(), nullable=True))
    op.add_column('service_orders', sa.Column('order_value', sa.Integer(), nullable=False))
    op.add_column('service_orders', sa.Column('payable_amount', sa.Integer(), nullable=False))
    op.add_column('service_orders', sa.Column('payment_by_customer', sa.Integer(), nullable=False))
    op.add_column('service_orders', sa.Column('payment_pending', sa.Integer(), nullable=False))
    op.add_column('service_orders', sa.Column('paymet_method', sa.String(length=100), nullable=True))
    op.add_column('service_orders', sa.Column('payment_status', sa.String(length=100), nullable=True))
    op.add_column('service_orders', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'last_payment_date')
    op.drop_column('service_orders', 'payment_status')
    op.drop_column('service_orders', 'paymet_method')
    op.drop_column('service_orders', 'payment_pending')
    op.drop_column('service_orders', 'payment_by_customer')
    op.drop_column('service_orders', 'payable_amount')
    op.drop_column('service_orders', 'order_value')
    op.drop_column('service_orders', 'order_completion')
    op.drop_column('service_orders', 'order_placement')
    op.drop_column('service_orders', 'patient_id')
    op.drop_column('service_orders', 'service_name')
    # ### end Alembic commands ###
