"""service order with service id

Revision ID: 13bfa499416b
Revises: d115fb63138f
Create Date: 2022-06-08 14:51:14.699521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bfa499416b'
down_revision = 'd115fb63138f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('service_provider_type', sa.String(length=100), nullable=True),
    sa.Column('service_provider_id', sa.Integer(), nullable=True),
    sa.Column('service_provider_fee', sa.Integer(), nullable=True),
    sa.Column('service_provider_fee_paid', sa.Integer(), nullable=True),
    sa.Column('service_provider_fee_pending', sa.Integer(), nullable=True),
    sa.Column('service_provider_fee_last_update', sa.DateTime(), nullable=True),
    sa.Column('service_provider_fee_status', sa.String(length=100), nullable=True),
    sa.Column('referral_type', sa.String(length=100), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('referral_provider_fee', sa.Integer(), nullable=True),
    sa.Column('referral_provider_fee_paid', sa.Integer(), nullable=True),
    sa.Column('referral_provider_fee_pending', sa.Integer(), nullable=True),
    sa.Column('referral_provider_fee_last_update', sa.DateTime(), nullable=True),
    sa.Column('referral_provider_fee_status', sa.String(length=100), nullable=True),
    sa.Column('current_address', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_order')
    # ### end Alembic commands ###
