"""clinic logo and start time

Revision ID: 14a00a688a6d
Revises: 522f54e60181
Create Date: 2022-11-21 13:14:28.683607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14a00a688a6d'
down_revision = '522f54e60181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_details', sa.Column('logo_image_id', sa.Integer(), nullable=True))
    op.add_column('clinic_details', sa.Column('contact_us', sa.Text(), nullable=True))
    op.add_column('clinic_details', sa.Column('starting_time', sa.Time(), nullable=True))
    op.add_column('clinic_details', sa.Column('ending_time', sa.Time(), nullable=True))
    op.drop_column('clinic_details', 'contuct_us')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_details', sa.Column('contuct_us', mysql.TEXT(), nullable=True))
    op.drop_column('clinic_details', 'ending_time')
    op.drop_column('clinic_details', 'starting_time')
    op.drop_column('clinic_details', 'contact_us')
    op.drop_column('clinic_details', 'logo_image_id')
    # ### end Alembic commands ###
