"""clinic activity

Revision ID: 1cc8226cd639
Revises: 3ae46bcc972a
Create Date: 2022-11-01 17:25:37.343678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cc8226cd639'
down_revision = '3ae46bcc972a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('service_received_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clinic_patient_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_patient_activity',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('clinic_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('service_received_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name='clinic_patient_activity_ibfk_1'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='clinic_patient_activity_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('clinic_activity')
    # ### end Alembic commands ###
