"""doctor schedule booked by added

Revision ID: 1d0a99498c9f
Revises: e389ef00e4d9
Create Date: 2022-09-17 10:37:06.061622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0a99498c9f'
down_revision = 'e389ef00e4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedules', sa.Column('booked_by_patient_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_schedules', 'booked_by_patient_id')
    # ### end Alembic commands ###
