"""doctor speciality column add again

Revision ID: 22f4aadcdb39
Revises: ff4945795c7b
Create Date: 2022-08-31 10:35:28.068605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f4aadcdb39'
down_revision = 'ff4945795c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
