"""doc chamber fee remove

Revision ID: 2a6fab1160bb
Revises: 92adfbfb7434
Create Date: 2022-08-30 17:06:45.879763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a6fab1160bb'
down_revision = '92adfbfb7434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_chambers', 'chamber_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_chambers', sa.Column('chamber_fee', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
