"""dr workplace priority

Revision ID: 2d66005008c9
Revises: e2016bfa225d
Create Date: 2022-11-14 12:12:30.266627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d66005008c9'
down_revision = 'e2016bfa225d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_workplace', sa.Column('top_priority', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_workplace', 'top_priority')
    # ### end Alembic commands ###
