"""date to booked date

Revision ID: 2f613b1b246c
Revises: 8182dc827957
Create Date: 2022-07-07 14:51:56.992877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f613b1b246c'
down_revision = '8182dc827957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemedicine_orders', sa.Column('booked_date', sa.Date(), nullable=True))
    op.drop_column('telemedicine_orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemedicine_orders', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('telemedicine_orders', 'booked_date')
    # ### end Alembic commands ###
