"""doc chamber fee

Revision ID: 3097d258980b
Revises: e1ad9ef10a28
Create Date: 2022-08-30 16:56:14.441000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3097d258980b'
down_revision = 'e1ad9ef10a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_chambers', sa.Column('chamber_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_chambers', 'chamber_fee')
    # ### end Alembic commands ###
