"""pharmacy: trade license update

Revision ID: 329ead4e61df
Revises: c66f031a0aff
Create Date: 2022-11-05 12:46:05.975516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329ead4e61df'
down_revision = 'c66f031a0aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy', sa.Column('trade_license', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy', 'trade_license')
    # ### end Alembic commands ###
