"""speciality in doc academic

Revision ID: 35ba223d2c4d
Revises: bec4dc18545f
Create Date: 2022-08-23 13:05:57.185297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ba223d2c4d'
down_revision = 'bec4dc18545f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_academic_info', sa.Column('speciality', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_academic_info', 'speciality')
    # ### end Alembic commands ###
