"""pharmacy active field

Revision ID: 38aa7af03632
Revises: edabbb0477a9
Create Date: 2022-09-19 16:39:03.016204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aa7af03632'
down_revision = 'edabbb0477a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy', sa.Column('pharmacy_is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy', 'pharmacy_is_active')
    # ### end Alembic commands ###
