"""health partners name fix

Revision ID: 38e4b0fd0e4a
Revises: 0b3414555b78
Create Date: 2022-05-17 16:30:39.580367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38e4b0fd0e4a'
down_revision = '0b3414555b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('detail_address', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('contact_person_phone', sa.String(length=100), nullable=False),
    sa.Column('contact_person_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('health_partner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_partner',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('district', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('detail_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_person_phone', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact_person_email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('health_partners')
    # ### end Alembic commands ###
