"""medicine take service id

Revision ID: 3fd2bdec02f9
Revises: f35126923fd4
Create Date: 2022-06-11 17:17:00.625863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd2bdec02f9'
down_revision = 'f35126923fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
