"""add: patient_name in ep table

Revision ID: 408364b6a3fa
Revises: 7f49b1dbe8ef
Create Date: 2023-01-11 13:25:23.683911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408364b6a3fa'
down_revision = '7f49b1dbe8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eprescriptions', sa.Column('patient_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eprescriptions', 'patient_phone')
    # ### end Alembic commands ###
