"""schedule server defaul added

Revision ID: 4443596de813
Revises: 7e1d2301939a
Create Date: 2022-04-21 12:05:48.225314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4443596de813'
down_revision = '7e1d2301939a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
