"""corporate partner

Revision ID: 4d7ca10e9d25
Revises: 8303908c97d1
Create Date: 2022-06-04 12:11:01.994632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d7ca10e9d25'
down_revision = '8303908c97d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_partner_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('detail_address', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('contact_person_phone', sa.String(length=100), nullable=False),
    sa.Column('contact_person_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doctor_schedules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('others', mysql.TEXT(), nullable=True),
    sa.Column('chamber_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('doctor_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], name='doctor_schedules_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('corporate_partners')
    op.drop_table('corporate_partner_users')
    # ### end Alembic commands ###
