"""health plan table modified

Revision ID: 4f7688e13add
Revises: c2eeb012694d
Create Date: 2022-07-02 15:37:56.970164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f7688e13add'
down_revision = 'c2eeb012694d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_plan_for_patient', sa.Column('register_by_id', sa.Integer(), nullable=False))
    op.add_column('health_plan_for_patient', sa.Column('registered_date', sa.Date(), nullable=True))
    op.add_column('health_plan_for_patient', sa.Column('fixed_amount', sa.Boolean(), nullable=False))
    op.add_column('health_plan_for_patient', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('health_plan_for_patient', 'register_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_plan_for_patient', sa.Column('register_by', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('health_plan_for_patient', 'amount')
    op.drop_column('health_plan_for_patient', 'fixed_amount')
    op.drop_column('health_plan_for_patient', 'registered_date')
    op.drop_column('health_plan_for_patient', 'register_by_id')
    # ### end Alembic commands ###
