"""pack size field

Revision ID: 522f54e60181
Revises: ee5148d4a4f4
Create Date: 2022-11-21 10:29:47.354669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522f54e60181'
down_revision = 'ee5148d4a4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_every_single_stock', sa.Column('pack_size', sa.String(length=100), nullable=True))
    op.add_column('pharmacy_purchase_single_order', sa.Column('pack_size', sa.String(length=100), nullable=True))
    op.add_column('pharmacy_single_grn', sa.Column('pack_size', sa.String(length=100), nullable=True))
    op.add_column('pharmacy_single_invoice', sa.Column('pack_size', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_single_invoice', 'pack_size')
    op.drop_column('pharmacy_single_grn', 'pack_size')
    op.drop_column('pharmacy_purchase_single_order', 'pack_size')
    op.drop_column('pharmacy_every_single_stock', 'pack_size')
    # ### end Alembic commands ###
