"""health plan days and fee add

Revision ID: 5c4640e10d00
Revises: 2f613b1b246c
Create Date: 2022-07-16 16:31:03.431165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4640e10d00'
down_revision = '2f613b1b246c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_plan_list', sa.Column('days', sa.Integer(), nullable=True))
    op.add_column('health_plan_list', sa.Column('fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_plan_list', 'fee')
    op.drop_column('health_plan_list', 'days')
    # ### end Alembic commands ###
