"""remove doctor schedule

Revision ID: 63a989093313
Revises: 98c248ef60e8
Create Date: 2022-09-16 00:18:57.214938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a989093313'
down_revision = '98c248ef60e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_schedules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minutes', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('am_pm', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='doctor_schedules_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
