"""patients: height weight remove

Revision ID: 6ca0f83d3545
Revises: 57ff905f6bfb
Create Date: 2022-03-27 14:47:36.975832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ca0f83d3545'
down_revision = '57ff905f6bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'height')
    op.drop_column('patients', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
