"""user_details relationship

Revision ID: 70f266bde0df
Revises: 8e05e9cd3b63
Create Date: 2022-02-28 17:52:55.959039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f266bde0df'
down_revision = '8e05e9cd3b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_details', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    op.drop_column('user_details', 'user_id')
    # ### end Alembic commands ###
