"""added again ep refer table

Revision ID: 7293019d320c
Revises: bb88475a013e
Create Date: 2022-11-07 12:32:37.822121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7293019d320c'
down_revision = 'bb88475a013e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ep_doctor_refer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ep_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ep_id'], ['eprescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ep_doctor_refer')
    # ### end Alembic commands ###
