"""chamber add in schedule

Revision ID: 7e1d2301939a
Revises: 6abb125f58ab
Create Date: 2022-04-20 14:49:49.684219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1d2301939a'
down_revision = '6abb125f58ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedules', sa.Column('chamber_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_schedules', 'chamber_id')
    # ### end Alembic commands ###
