"""service order pending date

Revision ID: 7fe0e2569f50
Revises: 618fb4d6bdee
Create Date: 2022-05-19 16:02:18.573425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe0e2569f50'
down_revision = '618fb4d6bdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('service_provider_fee_last_update', sa.Date(), nullable=True))
    op.add_column('service_orders', sa.Column('referral_provider_fee_last_update', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'referral_provider_fee_last_update')
    op.drop_column('service_orders', 'service_provider_fee_last_update')
    # ### end Alembic commands ###
