"""cc name change test

Revision ID: 8303908c97d1
Revises: bef82eab4f35
Create Date: 2022-06-04 10:47:12.300906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8303908c97d1'
down_revision = 'bef82eab4f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ep_chief_complaints_list', sa.Column('chief_complaints', sa.String(length=255), nullable=False))
    op.drop_column('ep_chief_complaints_list', 'cc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ep_chief_complaints_list', sa.Column('cc', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('ep_chief_complaints_list', 'chief_complaints')
    # ### end Alembic commands ###
