"""grn due and paid

Revision ID: 83ae097c2c0e
Revises: 398bb075a690
Create Date: 2022-10-23 16:46:02.051867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ae097c2c0e'
down_revision = '398bb075a690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_grn', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.add_column('pharmacy_grn', sa.Column('due_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_grn', 'due_amount')
    op.drop_column('pharmacy_grn', 'paid_amount')
    # ### end Alembic commands ###
