"""healthplan for patient with service order id

Revision ID: 8b0b86651eec
Revises: 32231e592e0f
Create Date: 2022-07-18 10:16:07.517913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0b86651eec'
down_revision = '32231e592e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_plan_for_patient', sa.Column('service_order_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_plan_for_patient', 'service_order_id')
    # ### end Alembic commands ###
