"""column: new service issuer id column remove in service_orders table

Revision ID: 8d210026a34e
Revises: 954313d0a710
Create Date: 2023-01-31 11:10:24.047728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d210026a34e'
down_revision = '954313d0a710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
