"""medicine list price field add

Revision ID: 8e745a56ae64
Revises: c9c808c4de7f
Create Date: 2022-06-16 11:27:29.164677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e745a56ae64'
down_revision = 'c9c808c4de7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ep_medicine_list', sa.Column('unit_type', sa.String(length=100), nullable=True))
    op.add_column('ep_medicine_list', sa.Column('unit_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ep_medicine_list', 'unit_price')
    op.drop_column('ep_medicine_list', 'unit_type')
    # ### end Alembic commands ###
