"""float append in patien_indicators

Revision ID: 90cd0a4dc37e
Revises: 34003d86897e
Create Date: 2022-05-16 10:53:55.651256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90cd0a4dc37e'
down_revision = '34003d86897e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_indicators', sa.Column('slot_flt4', sa.Float(), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_flt5', sa.Float(), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_flt6', sa.Float(), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_str7', sa.String(length=255), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_str8', sa.String(length=255), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_str9', sa.String(length=255), nullable=True))
    op.drop_column('patient_indicators', 'slot_str2')
    op.drop_column('patient_indicators', 'slot_str1')
    op.drop_column('patient_indicators', 'slot_str3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_indicators', sa.Column('slot_str3', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_str1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('patient_indicators', sa.Column('slot_str2', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('patient_indicators', 'slot_str9')
    op.drop_column('patient_indicators', 'slot_str8')
    op.drop_column('patient_indicators', 'slot_str7')
    op.drop_column('patient_indicators', 'slot_flt6')
    op.drop_column('patient_indicators', 'slot_flt5')
    op.drop_column('patient_indicators', 'slot_flt4')
    # ### end Alembic commands ###
