"""doc chamber int to float

Revision ID: 92adfbfb7434
Revises: 3097d258980b
Create Date: 2022-08-30 17:04:12.027750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92adfbfb7434'
down_revision = '3097d258980b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
