"""purchase order

Revision ID: 98c248ef60e8
Revises: 8eef4fc7e749
Create Date: 2022-09-14 14:22:02.771891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98c248ef60e8'
down_revision = '8eef4fc7e749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_purchase_single_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price_dp', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('payable_prize_dp', sa.Float(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['pharmacy_purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pharmacy_purchase_order', sa.Column('total_amount_dp', sa.Float(), nullable=True))
    op.add_column('pharmacy_purchase_order', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('pharmacy_purchase_order', sa.Column('payable_amount', sa.Float(), nullable=True))
    op.add_column('pharmacy_purchase_order', sa.Column('subtotal_amount', sa.Float(), nullable=True))
    op.drop_column('pharmacy_purchase_order', 'total_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_purchase_order', sa.Column('total_amount', mysql.FLOAT(), nullable=True))
    op.drop_column('pharmacy_purchase_order', 'subtotal_amount')
    op.drop_column('pharmacy_purchase_order', 'payable_amount')
    op.drop_column('pharmacy_purchase_order', 'discount')
    op.drop_column('pharmacy_purchase_order', 'total_amount_dp')
    op.drop_table('pharmacy_purchase_single_order')
    # ### end Alembic commands ###
