"""payment service order

Revision ID: 992d0e8805b4
Revises: 0a57af80a868
Create Date: 2022-06-12 10:38:27.440706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '992d0e8805b4'
down_revision = '0a57af80a868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.drop_column('service_orders', 'paymet_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('paymet_method', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('service_orders', 'payment_method')
    # ### end Alembic commands ###
