"""health plan plan type added

Revision ID: 9af217b95c93
Revises: af22fb6a7080
Create Date: 2022-09-03 12:17:53.125331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af217b95c93'
down_revision = 'af22fb6a7080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_plan_list', sa.Column('plan_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_plan_list', 'plan_type')
    # ### end Alembic commands ###
