"""health plan and for patient

Revision ID: 9e64130e0aa3
Revises: 188be3df4761
Create Date: 2022-06-25 14:50:05.068869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e64130e0aa3'
down_revision = '188be3df4761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_plan_for_patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('register_by', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_plan_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=100), nullable=True),
    sa.Column('total_patients', sa.Integer(), nullable=False),
    sa.Column('expire_status', sa.Boolean(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_plan_list')
    op.drop_table('health_plan_for_patient')
    # ### end Alembic commands ###
