"""e prescription years and moths

Revision ID: 9eb820e5260a
Revises: 9af217b95c93
Create Date: 2022-09-05 17:50:23.140141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eb820e5260a'
down_revision = '9af217b95c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eprescriptions', sa.Column('age_years', sa.Integer(), nullable=True))
    op.add_column('eprescriptions', sa.Column('age_months', sa.Integer(), nullable=True))
    op.drop_column('eprescriptions', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eprescriptions', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('eprescriptions', 'age_months')
    op.drop_column('eprescriptions', 'age_years')
    # ### end Alembic commands ###
