"""corporate user table fix

Revision ID: a5f6af9e1aac
Revises: 4d7ca10e9d25
Create Date: 2022-06-04 12:30:33.982060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f6af9e1aac'
down_revision = '4d7ca10e9d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_partner_users', sa.Column('corporate_id', sa.Integer(), nullable=False))
    op.add_column('corporate_partner_users', sa.Column('users_id', sa.Integer(), nullable=False))
    op.add_column('corporate_partner_users', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_partner_users', 'department')
    op.drop_column('corporate_partner_users', 'users_id')
    op.drop_column('corporate_partner_users', 'corporate_id')
    # ### end Alembic commands ###
