"""doctor qualification clumn added

Revision ID: a66628ba6347
Revises: b973134b88fb
Create Date: 2022-08-31 10:33:25.782237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66628ba6347'
down_revision = 'b973134b88fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_qualifications', sa.Column('qualification', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_qualifications', 'qualification')
    # ### end Alembic commands ###
