"""ep patient detail field add

Revision ID: a66ea7c5bb79
Revises: 7293019d320c
Create Date: 2022-11-07 16:43:10.553619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66ea7c5bb79'
down_revision = '7293019d320c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eprescriptions', sa.Column('patient_name', sa.String(length=100), nullable=True))
    op.add_column('eprescriptions', sa.Column('patient_sex', sa.String(length=10), nullable=True))
    op.add_column('eprescriptions', sa.Column('patient_age_years', sa.Integer(), nullable=True))
    op.add_column('eprescriptions', sa.Column('patient_age_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eprescriptions', 'patient_age_months')
    op.drop_column('eprescriptions', 'patient_age_years')
    op.drop_column('eprescriptions', 'patient_sex')
    op.drop_column('eprescriptions', 'patient_name')
    # ### end Alembic commands ###
