"""exp yr and online fees for doc

Revision ID: a87908232fac
Revises: 4c42fd904ae1
Create Date: 2022-07-21 12:46:38.600402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a87908232fac'
down_revision = '4c42fd904ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('exp_year', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('online_fees', sa.Float(), nullable=True))
    op.drop_column('doctors', 'main_chamber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('main_chamber', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('doctors', 'online_fees')
    op.drop_column('doctors', 'exp_year')
    # ### end Alembic commands ###
