"""table: new column add at e-prescription

Revision ID: a9ab68b0386c
Revises: 8676ba35d1b3
Create Date: 2023-01-15 15:08:17.797658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ab68b0386c'
down_revision = '8676ba35d1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
