"""schedule service id added

Revision ID: ab382f38dac2
Revises: 4443596de813
Create Date: 2022-04-25 11:34:47.372000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab382f38dac2'
down_revision = '4443596de813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedules', sa.Column('service_order_id', sa.Integer(), nullable=False))
    op.add_column('doctor_schedules', sa.Column('booked', sa.Boolean(), nullable=False))
    op.drop_column('doctor_schedules', 'pending')
    op.drop_column('doctor_schedules', 'payment')
    op.drop_column('doctor_schedules', 'payable_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedules', sa.Column('payable_amount', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctor_schedules', sa.Column('payment', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctor_schedules', sa.Column('pending', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('doctor_schedules', 'booked')
    op.drop_column('doctor_schedules', 'service_order_id')
    # ### end Alembic commands ###
