"""ep user id with null value

Revision ID: ab98dc3782e2
Revises: b158a8f2a33d
Create Date: 2022-11-22 15:17:58.162229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab98dc3782e2'
down_revision = 'b158a8f2a33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eprescriptions', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('eprescriptions', sa.Column('patient_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eprescriptions', 'patient_id')
    op.drop_column('eprescriptions', 'doctor_id')
    # ### end Alembic commands ###
