"""image log add name field

Revision ID: af197dadeac0
Revises: 1ac49e8dcb73
Create Date: 2022-05-26 11:09:11.474351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af197dadeac0'
down_revision = '1ac49e8dcb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_log', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_log', 'name')
    # ### end Alembic commands ###
