"""remove ep user id

Revision ID: b158a8f2a33d
Revises: 14a00a688a6d
Create Date: 2022-11-22 15:14:23.437313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b158a8f2a33d'
down_revision = '14a00a688a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eprescriptions_ibfk_2', 'eprescriptions', type_='foreignkey')
    op.drop_constraint('eprescriptions_ibfk_1', 'eprescriptions', type_='foreignkey')
    op.drop_column('eprescriptions', 'patient_id')
    op.drop_column('eprescriptions', 'doctor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eprescriptions', sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eprescriptions', sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('eprescriptions_ibfk_1', 'eprescriptions', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key('eprescriptions_ibfk_2', 'eprescriptions', 'users', ['patient_id'], ['id'])
    # ### end Alembic commands ###
