"""doctor qualification remove column

Revision ID: b973134b88fb
Revises: e9abd4acd1d1
Create Date: 2022-08-31 10:32:54.654967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b973134b88fb'
down_revision = 'e9abd4acd1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_qualifications', 'qualification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_qualifications', sa.Column('qualification', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
