"""ep before after

Revision ID: ba4d6da2d703
Revises: e79774b10e5f
Create Date: 2022-10-01 17:19:27.583587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4d6da2d703'
down_revision = 'e79774b10e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ep_medicines', sa.Column('before_after', sa.String(length=100), nullable=True))
    op.drop_column('ep_medicines', 'after_meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ep_medicines', sa.Column('after_meal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('ep_medicines', 'before_after')
    # ### end Alembic commands ###
