"""remove ep refer table

Revision ID: bb88475a013e
Revises: 329ead4e61df
Create Date: 2022-11-07 12:28:42.411416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb88475a013e'
down_revision = '329ead4e61df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ep_doctor_refer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ep_doctor_refer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('ep_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detail', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['ep_id'], ['eprescriptions.id'], name='ep_doctor_refer_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
