"""purchase order delivery filed add, clinic activity clinic_id, pharmacy trade_license remove

Revision ID: c66f031a0aff
Revises: 1cc8226cd639
Create Date: 2022-11-05 12:43:38.554782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c66f031a0aff'
down_revision = '1cc8226cd639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_activity', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clinic_activity', 'clinic', ['clinic_id'], ['id'])
    op.drop_index('trade_license', table_name='pharmacy')
    op.drop_column('pharmacy', 'trade_license')
    op.add_column('pharmacy_purchase_order', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('pharmacy_purchase_order', sa.Column('delivery_status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_purchase_order', 'delivery_status')
    op.drop_column('pharmacy_purchase_order', 'expected_delivery_date')
    op.add_column('pharmacy', sa.Column('trade_license', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('trade_license', 'pharmacy', ['trade_license'], unique=False)
    op.drop_constraint(None, 'clinic_activity', type_='foreignkey')
    op.drop_column('clinic_activity', 'clinic_id')
    # ### end Alembic commands ###
