"""schedule online

Revision ID: cdcf224019f9
Revises: 29d93a4016ac
Create Date: 2022-07-17 13:59:28.431951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcf224019f9'
down_revision = '29d93a4016ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedules', sa.Column('online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_schedules', 'online')
    # ### end Alembic commands ###
