"""doc chamber fee float add again

Revision ID: ce4152994aad
Revises: 2a6fab1160bb
Create Date: 2022-08-30 17:07:12.744820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4152994aad'
down_revision = '2a6fab1160bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_chambers', sa.Column('chamber_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_chambers', 'chamber_fee')
    # ### end Alembic commands ###
