"""clinic license

Revision ID: def757c115ee
Revises: 2d66005008c9
Create Date: 2022-11-16 17:14:29.071540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def757c115ee'
down_revision = '2d66005008c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
