"""doctor others activity add user id

Revision ID: e1ad9ef10a28
Revises: c2bd714f1bd7
Create Date: 2022-08-30 10:23:24.596336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ad9ef10a28'
down_revision = 'c2bd714f1bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_others_activity', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctor_others_activity', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_others_activity', type_='foreignkey')
    op.drop_column('doctor_others_activity', 'user_id')
    # ### end Alembic commands ###
