"""dr title

Revision ID: e2016bfa225d
Revises: 46b100387fc9
Create Date: 2022-11-14 12:05:54.823546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2016bfa225d'
down_revision = '46b100387fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('dr_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'dr_title')
    # ### end Alembic commands ###
