"""changed column name single_grn_id in single_stock table

Revision ID: e79774b10e5f
Revises: d07193f58bb0
Create Date: 2022-09-27 12:54:20.621231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e79774b10e5f'
down_revision = 'd07193f58bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_every_single_stock', sa.Column('single_grn_id', sa.Integer(), nullable=True))
    op.drop_constraint('pharmacy_every_single_stock_ibfk_2', 'pharmacy_every_single_stock', type_='foreignkey')
    op.create_foreign_key(None, 'pharmacy_every_single_stock', 'pharmacy_single_grn', ['single_grn_id'], ['id'])
    op.drop_column('pharmacy_every_single_stock', 'single_grn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_every_single_stock', sa.Column('single_grn', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pharmacy_every_single_stock', type_='foreignkey')
    op.create_foreign_key('pharmacy_every_single_stock_ibfk_2', 'pharmacy_every_single_stock', 'pharmacy_single_grn', ['single_grn'], ['id'])
    op.drop_column('pharmacy_every_single_stock', 'single_grn_id')
    # ### end Alembic commands ###
