"""health plan id added

Revision ID: e7bf635f187a
Revises: 9e64130e0aa3
Create Date: 2022-06-25 16:52:30.221733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bf635f187a'
down_revision = '9e64130e0aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
