"""doctor qualification turn into text

Revision ID: e9abd4acd1d1
Revises: ce4152994aad
Create Date: 2022-08-31 10:29:54.762646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9abd4acd1d1'
down_revision = 'ce4152994aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
