"""doctor chamber address

Revision ID: ed6534c56873
Revises: 8b0b86651eec
Create Date: 2022-07-18 14:39:32.575849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6534c56873'
down_revision = '8b0b86651eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_chambers', sa.Column('district', sa.String(length=100), nullable=False))
    op.add_column('doctor_chambers', sa.Column('detail_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_chambers', 'detail_address')
    op.drop_column('doctor_chambers', 'district')
    # ### end Alembic commands ###
