"""order status and medicine total mrp

Revision ID: efb390741ccc
Revises: 6651e0271cc1
Create Date: 2022-06-25 17:48:51.478052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb390741ccc'
down_revision = '6651e0271cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_orders', sa.Column('total_mrp', sa.Float(), nullable=False))
    op.add_column('service_orders', sa.Column('order_status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'order_status')
    op.drop_column('medicine_orders', 'total_mrp')
    # ### end Alembic commands ###
