"""remove service id from medicine order

Revision ID: f35126923fd4
Revises: d4d29b8d5923
Create Date: 2022-06-11 16:33:06.396529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35126923fd4'
down_revision = 'd4d29b8d5923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
