"""medicine order all field bug

Revision ID: f837e6fef6fe
Revises: 992d0e8805b4
Create Date: 2022-06-12 10:49:03.051007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f837e6fef6fe'
down_revision = '992d0e8805b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_orders', sa.Column('service_order_id', sa.Integer(), nullable=False))
    op.add_column('medicine_orders', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('medicine_orders', sa.Column('generic', sa.String(length=100), nullable=True))
    op.add_column('medicine_orders', sa.Column('strength', sa.String(length=100), nullable=True))
    op.add_column('medicine_orders', sa.Column('pharmaceuticals', sa.String(length=100), nullable=True))
    op.add_column('medicine_orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('medicine_orders', sa.Column('unit_price_tp', sa.Integer(), nullable=True))
    op.add_column('medicine_orders', sa.Column('unit_price_mrp', sa.Integer(), nullable=False))
    op.add_column('medicine_orders', sa.Column('unit_discount_percent', sa.Integer(), nullable=False))
    op.add_column('medicine_orders', sa.Column('total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_orders', 'total')
    op.drop_column('medicine_orders', 'unit_discount_percent')
    op.drop_column('medicine_orders', 'unit_price_mrp')
    op.drop_column('medicine_orders', 'unit_price_tp')
    op.drop_column('medicine_orders', 'quantity')
    op.drop_column('medicine_orders', 'pharmaceuticals')
    op.drop_column('medicine_orders', 'strength')
    op.drop_column('medicine_orders', 'generic')
    op.drop_column('medicine_orders', 'name')
    op.drop_column('medicine_orders', 'service_order_id')
    # ### end Alembic commands ###
