"""doctor speciality column remove

Revision ID: ff4945795c7b
Revises: a66628ba6347
Create Date: 2022-08-31 10:34:59.765385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff4945795c7b'
down_revision = 'a66628ba6347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_specialities', 'speciality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_specialities', sa.Column('speciality', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
