"""date into datetime

Revision ID: ffb3e858a335
Revises: 7fe0e2569f50
Create Date: 2022-05-19 16:10:23.351148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb3e858a335'
down_revision = '7fe0e2569f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
